import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { Camera, RotateCcw, X, Check } from "lucide-react";
import { useRef, useState, useEffect } from "react";
import { useLocation } from "wouter";
import { toast } from "sonner";

export default function Capture() {
  const [, setLocation] = useLocation();
  const videoRef = useRef<HTMLVideoElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [stream, setStream] = useState<MediaStream | null>(null);
  const [capturedImage, setCapturedImage] = useState<string | null>(null);
  const [isProcessing, setIsProcessing] = useState(false);
  const [facingMode, setFacingMode] = useState<"user" | "environment">("environment");

  const uploadFileMutation = trpc.files.upload.useMutation();
  const processImageMutation = trpc.ai.processImage.useMutation();

  // Start camera
  useEffect(() => {
    startCamera();
    return () => {
      stopCamera();
    };
  }, [facingMode]);

  const startCamera = async () => {
    try {
      const mediaStream = await navigator.mediaDevices.getUserMedia({
        video: {
          facingMode,
          width: { ideal: 1920 },
          height: { ideal: 1080 },
        },
      });
      setStream(mediaStream);
      if (videoRef.current) {
        videoRef.current.srcObject = mediaStream;
      }
    } catch (error) {
      console.error("Failed to start camera:", error);
      toast.error("Failed to access camera. Please check permissions.");
    }
  };

  const stopCamera = () => {
    if (stream) {
      stream.getTracks().forEach((track) => track.stop());
      setStream(null);
    }
  };

  const capturePhoto = () => {
    if (!videoRef.current || !canvasRef.current) return;

    const video = videoRef.current;
    const canvas = canvasRef.current;
    const context = canvas.getContext("2d");

    if (!context) return;

    // Set canvas size to video size
    canvas.width = video.videoWidth;
    canvas.height = video.videoHeight;

    // Draw video frame to canvas
    context.drawImage(video, 0, 0, canvas.width, canvas.height);

    // Get image as data URL
    const imageDataUrl = canvas.toDataURL("image/jpeg", 0.9);
    setCapturedImage(imageDataUrl);

    // Stop camera
    stopCamera();
  };

  const retakePhoto = () => {
    setCapturedImage(null);
    startCamera();
  };

  const switchCamera = () => {
    setFacingMode((prev) => (prev === "user" ? "environment" : "user"));
  };

  const processPhoto = async () => {
    if (!capturedImage) return;

    setIsProcessing(true);

    try {
      // Extract base64 data
      const base64Data = capturedImage.split(",")[1];

      // Create file record
      const fileName = `capture_${Date.now()}.jpg`;
      const fileRecord = await uploadFileMutation.mutateAsync({
        fileName,
        fileSize: base64Data.length,
        fileType: "image/jpeg",
      });

      // Process with AI
      const result = await processImageMutation.mutateAsync({
        fileId: fileRecord.fileId,
        fileBuffer: base64Data,
        fileName,
        autoGenerateDocument: true,
      });

      toast.success("Photo processed successfully!");

      // Navigate to document if created
      if (result.documentId) {
        setLocation(`/documents/${result.documentId}`);
      } else {
        setLocation("/dashboard");
      }
    } catch (error) {
      console.error("Failed to process photo:", error);
      toast.error("Failed to process photo. Please try again.");
      setIsProcessing(false);
    }
  };

  return (
    <DashboardLayout>
      <div className="space-y-6">
        <div>
          <h1 className="text-3xl font-bold mb-2">Capture Photo</h1>
          <p className="text-gray-600">
            Take a photo of a document, business card, or presentation
          </p>
        </div>

        <Card>
          <CardContent className="p-6">
            <div className="relative bg-black rounded-lg overflow-hidden" style={{ aspectRatio: "4/3" }}>
              {!capturedImage ? (
                <>
                  <video
                    ref={videoRef}
                    autoPlay
                    playsInline
                    className="w-full h-full object-cover"
                  />
                  <canvas ref={canvasRef} className="hidden" />

                  {/* Camera Controls */}
                  <div className="absolute bottom-6 left-0 right-0 flex items-center justify-center gap-4">
                    <Button
                      size="lg"
                      variant="secondary"
                      onClick={switchCamera}
                      className="rounded-full h-14 w-14 p-0"
                    >
                      <RotateCcw className="h-6 w-6" />
                    </Button>
                    <Button
                      size="lg"
                      onClick={capturePhoto}
                      className="rounded-full h-16 w-16 p-0 bg-white hover:bg-gray-100"
                      disabled={!stream}
                    >
                      <Camera className="h-8 w-8 text-gray-900" />
                    </Button>
                    <Button
                      size="lg"
                      variant="secondary"
                      onClick={() => setLocation("/dashboard")}
                      className="rounded-full h-14 w-14 p-0"
                    >
                      <X className="h-6 w-6" />
                    </Button>
                  </div>
                </>
              ) : (
                <>
                  <img
                    src={capturedImage}
                    alt="Captured"
                    className="w-full h-full object-cover"
                  />

                  {/* Preview Controls */}
                  <div className="absolute bottom-6 left-0 right-0 flex items-center justify-center gap-4">
                    <Button
                      size="lg"
                      variant="secondary"
                      onClick={retakePhoto}
                      disabled={isProcessing}
                      className="rounded-full"
                    >
                      <RotateCcw className="h-5 w-5 mr-2" />
                      Retake
                    </Button>
                    <Button
                      size="lg"
                      onClick={processPhoto}
                      disabled={isProcessing}
                      className="rounded-full bg-green-600 hover:bg-green-700"
                    >
                      {isProcessing ? (
                        <>
                          <div className="animate-spin h-5 w-5 border-2 border-white border-t-transparent rounded-full mr-2"></div>
                          Processing...
                        </>
                      ) : (
                        <>
                          <Check className="h-5 w-5 mr-2" />
                          Use Photo
                        </>
                      )}
                    </Button>
                  </div>
                </>
              )}
            </div>

            {/* Tips */}
            <div className="mt-6 bg-blue-50 border border-blue-200 rounded-lg p-4">
              <h3 className="font-semibold text-blue-900 mb-2">📸 Tips for Best Results</h3>
              <ul className="text-sm text-blue-800 space-y-1">
                <li>• Ensure good lighting and avoid shadows</li>
                <li>• Keep the camera steady and focus on the text</li>
                <li>• Position the document flat and parallel to the camera</li>
                <li>• Make sure all text is visible and not cut off</li>
              </ul>
            </div>
          </CardContent>
        </Card>
      </div>
    </DashboardLayout>
  );
}
