import { useEffect, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableHead, TableHeader, TableRow, TableCell } from "@/components/ui/table";
import { Skeleton } from "@/components/ui/skeleton";

interface LeaderboardEntry {
  rank: number;
  id: string;
  title: string;
  category: string;
  score: number;
  rating: number;
  metrics?: {
    accuracy?: number;
    latencyMs?: number;
    throughputQps?: number;
  };
}

interface LeaderboardResponse {
  generatedAt: string;
  leaderboard: LeaderboardEntry[];
}

export default function Leaderboard() {
  const [data, setData] = useState<LeaderboardResponse | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetch("/metrics/leaderboard.json")
      .then((res) => {
        if (!res.ok) {
          throw new Error("Failed to load leaderboard");
        }
        return res.json();
      })
      .then((json) => setData(json))
      .catch((err) => setError(err.message));
  }, []);

  return (
    <div className="min-h-screen bg-background">
      <div className="container py-10">
        <Card>
          <CardHeader>
            <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
              <div>
                <CardTitle className="text-3xl">Capability Leaderboard</CardTitle>
                <p className="text-sm text-muted-foreground">
                  Public evaluation results generated by the CI pipeline.
                </p>
              </div>
              {data?.generatedAt && (
                <Badge variant="secondary">Updated {new Date(data.generatedAt).toLocaleString()}</Badge>
              )}
            </div>
          </CardHeader>
          <CardContent>
            {error && (
              <div className="rounded-md border border-destructive/40 bg-destructive/10 p-4 text-sm text-destructive">
                {error}
              </div>
            )}
            {!data && !error ? (
              <div className="space-y-3">
                {Array.from({ length: 4 }).map((_, idx) => (
                  <Skeleton key={idx} className="h-8 w-full" />
                ))}
              </div>
            ) : null}
            {data && (
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Rank</TableHead>
                    <TableHead>Capability</TableHead>
                    <TableHead>Category</TableHead>
                    <TableHead>Score</TableHead>
                    <TableHead>Rating</TableHead>
                    <TableHead>Accuracy</TableHead>
                    <TableHead>Latency</TableHead>
                    <TableHead>Throughput</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {data.leaderboard.map((entry) => (
                    <TableRow key={entry.id}>
                      <TableCell>{entry.rank}</TableCell>
                      <TableCell className="font-medium">{entry.title}</TableCell>
                      <TableCell>
                        <Badge variant="outline" className="capitalize">
                          {entry.category}
                        </Badge>
                      </TableCell>
                      <TableCell>{parseFloat(String(entry.score)).toFixed(4)}</TableCell>
                      <TableCell>{parseFloat(String(entry.rating)).toFixed(1)}</TableCell>
                      <TableCell>{entry.metrics?.accuracy ? `${(entry.metrics.accuracy * 100).toFixed(1)}%` : "-"}</TableCell>
                      <TableCell>{entry.metrics?.latencyMs ? `${entry.metrics.latencyMs} ms` : "-"}</TableCell>
                      <TableCell>{entry.metrics?.throughputQps ? `${entry.metrics.throughputQps} QPS` : "-"}</TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
