import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableHead, TableHeader, TableRow, TableCell } from "@/components/ui/table";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";

interface LeaderboardEntry {
  rank: number;
  id: string;
  title: string;
  category: string;
  score: number;
  rating: number;
  metrics?: {
    accuracy?: number;
    latencyMs?: number;
    throughputQps?: number;
  };
}

interface LeaderboardResponse {
  generatedAt: string;
  leaderboard: LeaderboardEntry[];
}

export default function Leaderboard() {
  // Use tRPC endpoint instead of static JSON file
  const { data, error, isLoading } = trpc.agentCredit.getLeaderboard.useQuery({});

  // Handle both array and object response formats
  const leaderboardData = Array.isArray(data) ? data : (data as any)?.leaderboard || [];
  const generatedAt = Array.isArray(data) ? null : (data as any)?.generatedAt;

  return (
    <div className="min-h-screen bg-background">
      <div className="container py-10">
        <Card>
          <CardHeader>
            <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
              <div>
                <CardTitle className="text-3xl">Capability Leaderboard</CardTitle>
                <p className="text-sm text-muted-foreground">
                  Public evaluation results generated by the CI pipeline.
                </p>
              </div>
              {generatedAt && (
                <Badge variant="secondary">Updated {new Date(generatedAt).toLocaleString()}</Badge>
              )}
            </div>
          </CardHeader>
          <CardContent>
            {error && (
              <div className="rounded-md border border-destructive/40 bg-destructive/10 p-4 text-sm text-destructive">
                {error.message}
              </div>
            )}
            {isLoading ? (
              <div className="space-y-3">
                {Array.from({ length: 4 }).map((_, idx) => (
                  <Skeleton key={idx} className="h-8 w-full" />
                ))}
              </div>
            ) : null}
            {data && (
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Rank</TableHead>
                    <TableHead>Capability</TableHead>
                    <TableHead>Category</TableHead>
                    <TableHead>Score</TableHead>
                    <TableHead>Rating</TableHead>
                    <TableHead>Accuracy</TableHead>
                    <TableHead>Latency</TableHead>
                    <TableHead>Throughput</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {leaderboardData.map((entry: any) => (
                    <TableRow key={entry.id}>
                      <TableCell>{entry.rank}</TableCell>
                      <TableCell className="font-medium">{entry.title}</TableCell>
                      <TableCell>
                        <Badge variant="outline" className="capitalize">
                          {entry.category}
                        </Badge>
                      </TableCell>
                      <TableCell>{parseFloat(String(entry.score)).toFixed(4)}</TableCell>
                      <TableCell>{parseFloat(String(entry.rating)).toFixed(1)}</TableCell>
                      <TableCell>{entry.metrics?.accuracy ? `${(entry.metrics.accuracy * 100).toFixed(1)}%` : "-"}</TableCell>
                      <TableCell>{entry.metrics?.latencyMs ? `${entry.metrics.latencyMs} ms` : "-"}</TableCell>
                      <TableCell>{entry.metrics?.throughputQps ? `${entry.metrics.throughputQps} QPS` : "-"}</TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
