import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { trpc } from "@/lib/trpc";
import { Upload as UploadIcon, X, FileImage, CheckCircle, AlertCircle } from "lucide-react";
import { useState, useCallback, useRef } from "react";
import { useLocation } from "wouter";
import { toast } from "sonner";

interface UploadedFile {
  file: File;
  preview: string;
  status: "pending" | "uploading" | "processing" | "completed" | "error";
  progress: number;
  fileId?: number;
  documentId?: number;
  error?: string;
}

export default function Upload() {
  const [, setLocation] = useLocation();
  const [uploadedFiles, setUploadedFiles] = useState<UploadedFile[]>([]);
  const [isDragging, setIsDragging] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const uploadFileMutation = trpc.files.upload.useMutation();
  const processImageMutation = trpc.ai.processImage.useMutation();

  const handleFiles = useCallback((files: FileList | null) => {
    if (!files) return;

    const newFiles: UploadedFile[] = Array.from(files)
      .filter((file) => file.type.startsWith("image/"))
      .map((file) => ({
        file,
        preview: URL.createObjectURL(file),
        status: "pending" as const,
        progress: 0,
      }));

    if (newFiles.length === 0) {
      toast.error("Please select image files only");
      return;
    }

    setUploadedFiles((prev) => [...prev, ...newFiles]);

    // Auto-start upload
    newFiles.forEach((fileData) => {
      uploadFile(fileData);
    });
  }, []);

  const uploadFile = async (fileData: UploadedFile) => {
    try {
      // Update status to uploading
      setUploadedFiles((prev) =>
        prev.map((f) => (f.file === fileData.file ? { ...f, status: "uploading", progress: 30 } : f))
      );

      // Read file as base64
      const reader = new FileReader();
      const base64Promise = new Promise<string>((resolve, reject) => {
        reader.onload = () => {
          const result = reader.result as string;
          const base64 = result.split(",")[1]; // Remove data:image/...;base64, prefix
          resolve(base64);
        };
        reader.onerror = reject;
        reader.readAsDataURL(fileData.file);
      });

      const base64Data = await base64Promise;

      // Create file record in database
      const fileRecord = await uploadFileMutation.mutateAsync({
        fileName: fileData.file.name,
        fileSize: fileData.file.size,
        fileType: fileData.file.type,
      });

      setUploadedFiles((prev) =>
        prev.map((f) =>
          f.file === fileData.file ? { ...f, fileId: fileRecord.fileId, progress: 50 } : f
        )
      );

      // Process image with AI
      setUploadedFiles((prev) =>
        prev.map((f) => (f.file === fileData.file ? { ...f, status: "processing", progress: 70 } : f))
      );

      const result = await processImageMutation.mutateAsync({
        fileId: fileRecord.fileId,
        fileBuffer: base64Data,
        fileName: fileData.file.name,
        autoGenerateDocument: true,
      });

      // Update status to completed
      setUploadedFiles((prev) =>
        prev.map((f) =>
          f.file === fileData.file
            ? {
                ...f,
                status: "completed",
                progress: 100,
                documentId: result.documentId,
              }
            : f
        )
      );

      toast.success(`Successfully processed ${fileData.file.name}`);
    } catch (error) {
      console.error("Upload failed:", error);
      setUploadedFiles((prev) =>
        prev.map((f) =>
          f.file === fileData.file
            ? {
                ...f,
                status: "error",
                error: error instanceof Error ? error.message : "Upload failed",
              }
            : f
        )
      );
      toast.error(`Failed to process ${fileData.file.name}`);
    }
  };

  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(true);
  }, []);

  const handleDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
  }, []);

  const handleDrop = useCallback(
    (e: React.DragEvent) => {
      e.preventDefault();
      setIsDragging(false);
      handleFiles(e.dataTransfer.files);
    },
    [handleFiles]
  );

  const handleFileInput = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      handleFiles(e.target.files);
    },
    [handleFiles]
  );

  const removeFile = (fileData: UploadedFile) => {
    URL.revokeObjectURL(fileData.preview);
    setUploadedFiles((prev) => prev.filter((f) => f.file !== fileData.file));
  };

  const viewDocument = (documentId: number) => {
    setLocation(`/documents/${documentId}`);
  };

  return (
    <DashboardLayout>
      <div className="space-y-6">
        <div>
          <h1 className="text-3xl font-bold mb-2">Upload Images</h1>
          <p className="text-gray-600">
            Upload photos of documents, business cards, or presentations to extract text and generate knowledge documents
          </p>
        </div>

        {/* Upload Area */}
        <Card>
          <CardContent className="p-8">
            <div
              className={`border-2 border-dashed rounded-lg p-12 text-center transition-all ${
                isDragging
                  ? "border-blue-500 bg-blue-50"
                  : "border-gray-300 hover:border-gray-400"
              }`}
              onDragOver={handleDragOver}
              onDragLeave={handleDragLeave}
              onDrop={handleDrop}
            >
              <UploadIcon className="h-16 w-16 text-gray-400 mx-auto mb-4" />
              <h3 className="text-xl font-semibold mb-2">
                Drag and drop images here
              </h3>
              <p className="text-gray-600 mb-4">or</p>
              <Button
                onClick={() => fileInputRef.current?.click()}
                size="lg"
              >
                Select Files
              </Button>
              <input
                ref={fileInputRef}
                type="file"
                accept="image/*"
                multiple
                className="hidden"
                onChange={handleFileInput}
              />
              <p className="text-sm text-gray-500 mt-4">
                Supports: JPG, PNG, WEBP, GIF (Max 10MB per file)
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Uploaded Files List */}
        {uploadedFiles.length > 0 && (
          <div>
            <h2 className="text-2xl font-bold mb-4">Processing Files</h2>
            <div className="space-y-4">
              {uploadedFiles.map((fileData, index) => (
                <Card key={index}>
                  <CardContent className="p-6">
                    <div className="flex items-start gap-4">
                      {/* Preview */}
                      <div className="flex-shrink-0">
                        <img
                          src={fileData.preview}
                          alt={fileData.file.name}
                          className="h-20 w-20 object-cover rounded-lg border"
                        />
                      </div>

                      {/* File Info */}
                      <div className="flex-1 min-w-0">
                        <div className="flex items-start justify-between mb-2">
                          <div className="flex-1 min-w-0">
                            <h3 className="font-semibold truncate">
                              {fileData.file.name}
                            </h3>
                            <p className="text-sm text-gray-500">
                              {(fileData.file.size / 1024 / 1024).toFixed(2)} MB
                            </p>
                          </div>
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => removeFile(fileData)}
                            disabled={fileData.status === "uploading" || fileData.status === "processing"}
                          >
                            <X className="h-4 w-4" />
                          </Button>
                        </div>

                        {/* Status */}
                        <div className="space-y-2">
                          {fileData.status === "pending" && (
                            <div className="flex items-center gap-2 text-gray-600">
                              <FileImage className="h-4 w-4" />
                              <span className="text-sm">Pending...</span>
                            </div>
                          )}
                          {(fileData.status === "uploading" || fileData.status === "processing") && (
                            <>
                              <div className="flex items-center gap-2 text-blue-600">
                                <div className="animate-spin h-4 w-4 border-2 border-blue-600 border-t-transparent rounded-full"></div>
                                <span className="text-sm">
                                  {fileData.status === "uploading" ? "Uploading..." : "Processing with AI..."}
                                </span>
                              </div>
                              <Progress value={fileData.progress} className="h-2" />
                            </>
                          )}
                          {fileData.status === "completed" && (
                            <div className="flex items-center justify-between">
                              <div className="flex items-center gap-2 text-green-600">
                                <CheckCircle className="h-4 w-4" />
                                <span className="text-sm">Completed</span>
                              </div>
                              {fileData.documentId && (
                                <Button
                                  size="sm"
                                  onClick={() => viewDocument(fileData.documentId!)}
                                >
                                  View Document
                                </Button>
                              )}
                            </div>
                          )}
                          {fileData.status === "error" && (
                            <div className="flex items-center gap-2 text-red-600">
                              <AlertCircle className="h-4 w-4" />
                              <span className="text-sm">{fileData.error || "Failed"}</span>
                            </div>
                          )}
                        </div>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        )}
      </div>
    </DashboardLayout>
  );
}
