/**
 * Workflow Results Dialog
 *
 * Displays detailed workflow results including:
 * - Step outputs with syntax highlighting
 * - Shared memory visualization
 * - Export functionality (JSON/Markdown)
 */

import { useState } from 'react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { ScrollArea } from '@/components/ui/scroll-area';
import {
  Download,
  Copy,
  CheckCircle,
  XCircle,
  Clock,
  Brain,
  Database,
} from 'lucide-react';
import { toast } from 'sonner';

type StepResult = {
  agent: string;
  agentId: string;
  status: 'pending' | 'running' | 'completed' | 'failed';
  output?: any;
  error?: string;
  startedAt?: Date;
  completedAt?: Date;
  executionTime?: number;
};

type WorkflowResultsDialogProps = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  workflowId: string;
  task: string;
  status: string;
  orchestration: string;
  steps: StepResult[];
  sharedMemory?: Record<string, any>;
  executionTime?: number;
};

export default function WorkflowResultsDialog({
  open,
  onOpenChange,
  workflowId,
  task,
  status,
  orchestration,
  steps,
  sharedMemory = {},
  executionTime,
}: WorkflowResultsDialogProps) {
  const [copiedStep, setCopiedStep] = useState<string | null>(null);

  const formatDuration = (ms: number | null | undefined) => {
    if (!ms) return 'N/A';
    if (ms < 1000) return `${ms}ms`;
    if (ms < 60000) return `${(ms / 1000).toFixed(1)}s`;
    return `${(ms / 60000).toFixed(1)}m`;
  };

  const formatTimestamp = (date: Date | undefined) => {
    if (!date) return 'N/A';
    return new Date(date).toLocaleString();
  };

  const handleCopyStep = (stepIndex: number, content: string) => {
    navigator.clipboard.writeText(content);
    setCopiedStep(`step-${stepIndex}`);
    toast.success('Copied to clipboard');
    setTimeout(() => setCopiedStep(null), 2000);
  };

  const handleExportJSON = () => {
    const exportData = {
      workflowId,
      task,
      status,
      orchestration,
      executionTime,
      exportedAt: new Date().toISOString(),
      steps: steps.map((step) => ({
        agent: step.agent,
        agentId: step.agentId,
        status: step.status,
        output: step.output,
        error: step.error,
        startedAt: step.startedAt,
        completedAt: step.completedAt,
        executionTime: step.executionTime,
      })),
      sharedMemory,
    };

    const blob = new Blob([JSON.stringify(exportData, null, 2)], {
      type: 'application/json',
    });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `workflow-${workflowId}-${new Date().toISOString().split('T')[0]}.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success('Exported as JSON');
  };

  const handleExportMarkdown = () => {
    const markdown = `# Workflow Results: ${task}

**Workflow ID:** \`${workflowId}\`
**Status:** ${status}
**Orchestration:** ${orchestration}
**Execution Time:** ${formatDuration(executionTime)}
**Exported:** ${new Date().toISOString()}

---

## Steps

${steps
  .map(
    (step, index) => `
### ${index + 1}. ${step.agent}

- **Agent ID:** \`${step.agentId}\`
- **Status:** ${step.status}
- **Started:** ${formatTimestamp(step.startedAt)}
- **Completed:** ${formatTimestamp(step.completedAt)}
- **Duration:** ${formatDuration(step.executionTime)}

${step.error ? `**Error:**\n\`\`\`\n${step.error}\n\`\`\`` : ''}

${
  step.output
    ? `**Output:**\n\`\`\`json\n${JSON.stringify(step.output, null, 2)}\n\`\`\``
    : ''
}
`
  )
  .join('\n---\n')}

---

## Shared Memory

\`\`\`json
${JSON.stringify(sharedMemory, null, 2)}
\`\`\`

---

*Generated by Awareness Market AI Collaboration*
`;

    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `workflow-${workflowId}-${new Date().toISOString().split('T')[0]}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success('Exported as Markdown');
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'completed':
        return <CheckCircle className="w-4 h-4 text-green-400" />;
      case 'failed':
        return <XCircle className="w-4 h-4 text-red-400" />;
      case 'running':
        return <Clock className="w-4 h-4 text-blue-400 animate-spin" />;
      default:
        return <Clock className="w-4 h-4 text-gray-400" />;
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-4xl max-h-[80vh] glass-panel">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-xl">
            <Brain className="w-6 h-6 text-primary" />
            Workflow Results
          </DialogTitle>
          <DialogDescription>
            View detailed outputs and export results
          </DialogDescription>
        </DialogHeader>

        {/* Export Buttons */}
        <div className="flex items-center gap-2 py-2 border-b border-border">
          <Button
            size="sm"
            variant="outline"
            onClick={handleExportJSON}
            className="gap-2"
          >
            <Download className="w-4 h-4" />
            Export JSON
          </Button>
          <Button
            size="sm"
            variant="outline"
            onClick={handleExportMarkdown}
            className="gap-2"
          >
            <Download className="w-4 h-4" />
            Export Markdown
          </Button>
        </div>

        <Tabs defaultValue="steps" className="flex-1">
          <TabsList className="grid w-full grid-cols-2">
            <TabsTrigger value="steps">
              <Brain className="w-4 h-4 mr-2" />
              Steps Output
            </TabsTrigger>
            <TabsTrigger value="memory">
              <Database className="w-4 h-4 mr-2" />
              Shared Memory
            </TabsTrigger>
          </TabsList>

          {/* Steps Tab */}
          <TabsContent value="steps" className="flex-1">
            <ScrollArea className="h-[500px] pr-4">
              <div className="space-y-4">
                {steps.map((step, index) => (
                  <div
                    key={index}
                    className="glass-subtle rounded-lg p-4 space-y-3"
                  >
                    {/* Step Header */}
                    <div className="flex items-start justify-between">
                      <div className="flex items-center gap-3">
                        <div className="flex items-center justify-center w-8 h-8 rounded-full bg-primary/20 text-primary font-mono text-sm">
                          {index + 1}
                        </div>
                        <div>
                          <div className="font-semibold text-foreground">
                            {step.agent}
                          </div>
                          <div className="text-xs text-muted-foreground">
                            {step.agentId}
                          </div>
                        </div>
                      </div>
                      <div className="flex items-center gap-2">
                        {getStatusIcon(step.status)}
                        <Badge
                          variant={
                            step.status === 'completed'
                              ? 'default'
                              : step.status === 'failed'
                              ? 'destructive'
                              : 'outline'
                          }
                        >
                          {step.status}
                        </Badge>
                      </div>
                    </div>

                    {/* Step Metadata */}
                    <div className="grid grid-cols-3 gap-2 text-xs text-muted-foreground">
                      <div>
                        <span className="font-medium">Started:</span>{' '}
                        {formatTimestamp(step.startedAt)}
                      </div>
                      <div>
                        <span className="font-medium">Completed:</span>{' '}
                        {formatTimestamp(step.completedAt)}
                      </div>
                      <div>
                        <span className="font-medium">Duration:</span>{' '}
                        {formatDuration(step.executionTime)}
                      </div>
                    </div>

                    {/* Error Display */}
                    {step.error && (
                      <div className="bg-red-500/10 border border-red-500/50 rounded p-3">
                        <div className="text-sm font-medium text-red-400 mb-1">
                          Error
                        </div>
                        <pre className="text-xs text-red-300 overflow-x-auto">
                          {step.error}
                        </pre>
                      </div>
                    )}

                    {/* Output Display */}
                    {step.output && (
                      <div className="space-y-2">
                        <div className="flex items-center justify-between">
                          <span className="text-sm font-medium text-foreground">
                            Output
                          </span>
                          <Button
                            size="sm"
                            variant="ghost"
                            onClick={() =>
                              handleCopyStep(
                                index,
                                JSON.stringify(step.output, null, 2)
                              )
                            }
                            className="h-6 px-2"
                          >
                            {copiedStep === `step-${index}` ? (
                              <CheckCircle className="w-3 h-3" />
                            ) : (
                              <Copy className="w-3 h-3" />
                            )}
                          </Button>
                        </div>
                        <pre className="bg-black/20 rounded p-3 text-xs text-foreground overflow-x-auto">
                          {JSON.stringify(step.output, null, 2)}
                        </pre>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </ScrollArea>
          </TabsContent>

          {/* Shared Memory Tab */}
          <TabsContent value="memory" className="flex-1">
            <ScrollArea className="h-[500px]">
              <div className="glass-subtle rounded-lg p-4">
                {Object.keys(sharedMemory).length > 0 ? (
                  <pre className="text-xs text-foreground overflow-x-auto">
                    {JSON.stringify(sharedMemory, null, 2)}
                  </pre>
                ) : (
                  <div className="text-center py-12 text-muted-foreground">
                    <Database className="w-12 h-12 mx-auto mb-3 opacity-50" />
                    <p>No shared memory available</p>
                  </div>
                )}
              </div>
            </ScrollArea>
          </TabsContent>
        </Tabs>
      </DialogContent>
    </Dialog>
  );
}
